openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/phone/verify/hook:
    post:
      summary: ''
      operationId: postApiPhoneVerifyHook
      description: ''
      parameters: []
      responses: {  }
      tags:
        - AuthPhone
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  description: ''
                  example: voluptas
                  nullable: false
                phone:
                  type: string
                  description: ''
                  example: praesentium
                  nullable: false
              required:
                - key
                - phone
      security: []
tags:
  -
    name: AuthPhone
    description: 'Авторизация пользователей через телефон.'
