openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/login:
    post:
      summary: Login
      operationId: login
      description: 'Авторизация пользователя'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: messages.auth.login.success
                  access_token: 3|OnfjrdKtmnz2ysgeEWJNTCExlBq3eV0Ga7nRxCR54b7ce52c
                  token_type: Bearer
                  user:
                    name: 'Фёдоров Святослав Владимирович'
                    email: veselov.leonid@example.com
                    roles: []
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: messages.auth.login.success
                  access_token:
                    type: string
                    example: 3|OnfjrdKtmnz2ysgeEWJNTCExlBq3eV0Ga7nRxCR54b7ce52c
                  token_type:
                    type: string
                    example: Bearer
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                        example: 'Фёдоров Святослав Владимирович'
                      email:
                        type: string
                        example: veselov.leonid@example.com
                      roles:
                        type: array
                        example: []
        403:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: messages.auth.login.error
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: messages.auth.login.error
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'validation.email The <code>email</code> of an existing record in the users table. validation.min.'
                  example: lessie.beer@example.org
                  nullable: false
                password:
                  type: string
                  description: validation.min.
                  example: '8B]CSP=BDMj;6\j)|y'
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: Register
      operationId: register
      description: 'Регистрация нового пользователя'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: messages.auth.register.success
                  access_token: 4|I6KbXkCssqMKhZ0kES6I6tyjbl5PFBXzBzgb0yMCaf9f7b2c
                  token_type: Bearer
                  user:
                    name: 'Симонова Яна Максимовна'
                    email: anastasiy42@example.org
                    roles: []
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: messages.auth.register.success
                  access_token:
                    type: string
                    example: 4|I6KbXkCssqMKhZ0kES6I6tyjbl5PFBXzBzgb0yMCaf9f7b2c
                  token_type:
                    type: string
                    example: Bearer
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                        example: 'Симонова Яна Максимовна'
                      email:
                        type: string
                        example: anastasiy42@example.org
                      roles:
                        type: array
                        example: []
        403:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: error
                  message: messages.auth.register.error
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: messages.auth.register.error
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'validation.min validation.max.'
                  example: tx
                  nullable: false
                email:
                  type: string
                  description: validation.email.
                  example: rosemarie73@example.org
                  nullable: false
                password:
                  type: string
                  description: validation.min.
                  example: Y-jptuNLm=
                  nullable: false
                password_confirmation:
                  type: string
                  description: 'The value and <code>password</code> must match.'
                  example: dignissimos
                  nullable: false
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/logout:
    post:
      summary: logout
      operationId: logout
      description: 'Выход пользователя'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: messages.auth.logout.success
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: messages.auth.logout.success
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: messages.auth.logout.error
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: messages.auth.logout.error
      tags:
        - Auth
  /api/roles-change:
    get:
      summary: GetChangeRoles
      operationId: getChangeRoles
      description: 'Получение ролей которые может сменить обычный пользователь'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    status: success
                    message: messages.role.get_change_role.success
                    role:
                      id: 1
                      name: Root
                  -
                    status: success
                    message: messages.role.get_change_role.success
                    role:
                      id: 1
                      name: Root
      tags:
        - Role
      security: []
    post:
      summary: ChangeRoleForDefaultUser
      operationId: changeRoleForDefaultUser
      description: 'Сменить роль для обычного пользователя'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: messages.role.change_role_for_default_user.success
                  user:
                    name: 'Тимофеева Люся Борисовна'
                    email: knosov@example.net
                    roles: []
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: messages.role.change_role_for_default_user.success
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                        example: 'Тимофеева Люся Борисовна'
                      email:
                        type: string
                        example: knosov@example.net
                      roles:
                        type: array
                        example: []
      tags:
        - Role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roleId:
                  type: integer
                  description: 'The <code>id</code> of an existing record in the roles table.'
                  example: 15
                  nullable: false
              required:
                - roleId
  /api/tracks:
    get:
      summary: get
      operationId: get
      description: 'Получение трасс по фильтрам'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    status: success
                    message: messages.track.get.success
                    tracks:
                      id: 27
                      name: 'Дементьева Варвара Романовна'
                      address: '060980, Магаданская область, город Кашира, наб. Славы, 22'
                      images: null
                      latitude: 0
                      longitude: 0
                  -
                    status: success
                    message: messages.track.get.success
                    tracks:
                      id: 28
                      name: 'Владлена Александровна Турова'
                      address: '953723, Московская область, город Павловский Посад, ул. Ленина, 14'
                      images: null
                      latitude: 0
                      longitude: 0
      tags:
        - Track
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: string
                  description: ''
                  example: null
                  nullable: true
                limit:
                  type: integer
                  description: validation.max.
                  example: 3
                  nullable: false
      security: []
    post:
      summary: create
      operationId: create
      description: 'Метод создания трека'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: messages.track.create.success
                  track:
                    id: 29
                    name: 'Кристина Владимировна Белозёрова'
                    address: '482300, Белгородская область, город Воскресенск, пр. Космонавтов, 72'
                    images: null
                    latitude: 0
                    longitude: 0
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: messages.track.create.success
                  track:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 29
                      name:
                        type: string
                        example: 'Кристина Владимировна Белозёрова'
                      address:
                        type: string
                        example: '482300, Белгородская область, город Воскресенск, пр. Космонавтов, 72'
                      images:
                        type: string
                        example: null
                      latitude:
                        type: integer
                        example: 0
                      longitude:
                        type: integer
                        example: 0
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: error
                  message: messages.track.create.error
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: messages.track.create.error
      tags:
        - Track
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: validation.min.
                  example: dspyprmwoveqxmuphewznsngpdhjwattpioduw
                  nullable: false
                address:
                  type: string
                  description: ''
                  example: at
                  nullable: false
                latitude:
                  type: number
                  description: validation.between.
                  example: -87
                  nullable: false
                longitude:
                  type: number
                  description: validation.between.
                  example: -180
                  nullable: false
                images:
                  type: array
                  description: 'validation.image validation.max.'
                  items:
                    type: string
                    format: binary
              required:
                - name
                - address
                - latitude
                - longitude
  /api/users:
    get:
      summary: GetUserForToken
      operationId: getUserForToken
      description: 'Получить данные пользователя по токену'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: messages.user.get_user_for_token.success
                  user:
                    name: 'Рафаил Львович Харитонов'
                    email: nikonov.larisa@example.org
                    roles: []
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: messages.user.get_user_for_token.success
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                        example: 'Рафаил Львович Харитонов'
                      email:
                        type: string
                        example: nikonov.larisa@example.org
                      roles:
                        type: array
                        example: []
      tags:
        - User
tags:
  -
    name: Auth
    description: 'Авторизация пользователей и всё что с ней связано.'
  -
    name: Role
    description: 'Методы взаимодествия с ролями'
  -
    name: Track
    description: 'Методы взаимодествия с трассами на которых проходят гонки'
  -
    name: User
    description: 'Методы манипуляции пользователем.'
