version: "3.8"

services:
    moto_backend:
        image: moskowpsix/moto-backend:develop
        env_file: .env
        volumes:
            - ./laravel:/var/www/moto_backend
        working_dir: /var/www/moto_backend

    nginx:
        image: nginx:latest
        volumes:
            - ./laravel/nginx/conf.d:/etc/nginx/conf.d
            - ./laravel:/var/www/moto_backend
        ports:
            - "100:80"

volumes:
    db_data:
