name: 'Moto Backend Deploy Develop'

on:
  push:
    branches: ['develop']
  pull_request:
    branches: [ "develop" ]

jobs:
  build-docker-backend-image:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            context: ./docker/php/
            file: ./docker/php/dockerfile
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/moto-backend:develop
            build-args: |
              GIT_TOKEN=${{ secrets.GIT_AUTH_TOKEN}}

  build-docker-nginx-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./docker/nginx/
          file: ./docker/nginx/dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moto-nginx:develop
          build-args: |
            GIT_TOKEN=${{ secrets.GIT_AUTH_TOKEN}}

  deploy-code-to-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_NAME }}
          password: ${{ secrets.DEV_SSH_PASSWORD }}
          port: ${{ secrets.DEV_SSH_PORT }}

          script: |
            cd ${{ secrets.DEV_PROJECT_DIR }};
            git checkout develop;
            git checkout -- .
            git -c credential.helper='!f() { echo "username=${{secrets.GIT_AUTH_NAME}}"; echo "password=${{secrets.GIT_AUTH_TOKEN}}"; }; f' pull
