name: 'Moto Backend Deploy Master'

on:
  push:
    branches: ['master']
  pull_request:
    branches: [ "master" ]

jobs:
  build-docker-backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./docker/php/
          file: ./docker/php/dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moto-backend:master
          build-args: |
            GIT_TOKEN=${{ secrets.GIT_AUTH_TOKEN}}

  build-docker-nginx-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./docker/nginx/
          file: ./docker/nginx/dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moto-nginx:master
          build-args: |
            GIT_TOKEN=${{ secrets.GIT_AUTH_TOKEN}}

  deploy-code-to-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_NAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}

          script: |
            cd ${{ secrets.PROD_PROJECT_DIR }};
            git checkout master;
            git -c credential.helper='!f() { echo "username=${{secrets.GIT_AUTH_NAME}}"; echo "password=${{secrets.GIT_AUTH_TOKEN}}"; }; f' pull
